name: "Lint and Test"

on:
  pull_request: 
    branches: 
      - main
    types: 
      - "opened"
      - "synchronize"
      - "reopened"

env:
  AWS_REGION : "ap-northeast-1"
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
  TFSTATE_BUCKET: ${{ secrets.TFSTATE_BUCKET }}

permissions:
  id-token: write
  contents: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: "./app"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use nodejs
        uses: actions/setup-node@v4

      - name: Install deps
        run: npm ci
        
      - name: Run lint
        run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: "./app"
    permissions:
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use nodejs
        uses: actions/setup-node@v4

      - name: Install deps
        run: npm ci
        
      - name: Run test
        run: npm run test
      
      - name: Report coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          working-directory: "./app"

  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: "./terraform/prod"
    env:
      TF_VAR_github_org: ${{ secrets.ORGANIZATION_NAME }}
      TF_VAR_github_repository: ${{ secrets.REPOSITORY_NAME }}
      TF_VAR_s3_bucket_name: ${{ secrets.S3_BUCKET_NAME  }}
      TF_VAR_website_domain: ${{ secrets.WEBSITE_DOMAIN  }}
 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "^1.3.7"
          terraform_wrapper: false

      - name: Terraform init
        run: |
          terraform init -reconfigure \
            -migrate-state \
            -backend-config="bucket=${{ env.TFSTATE_BUCKET }}" \
            -backend-config="key=state/terraform.tfstate" \
            -backend-config="region=${{ env.AWS_REGION  }}"

      - name: Terraform plan
        run: terraform plan
