name: "AWS Deploy"

on:
  pull_request: 
    branches: 
      - main
    types: closed

env:
  AWS_REGION : "ap-northeast-1"
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
  TFSTATE_BUCKET: ${{ secrets.TFSTATE_BUCKET }}

permissions:
  id-token: write
  contents: write

jobs:
  lint:
    if: github.event.pull_request.merged == true
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: "./app"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use nodejs
        uses: actions/setup-node@v4

      - name: Install deps
        run: npm ci
        
      - name: Run lint
        run: npm run lint

  test:
    if: github.event.pull_request.merged == true
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: "./app"
    permissions:
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use nodejs
        uses: actions/setup-node@v4

      - name: Install deps
        run: npm ci
        
      - name: Run test
        run: npm run test
      
      - name: Report coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          working-directory: "./app"


  build:
    needs: ["lint", "test"]
    if: github.event.pull_request.merged == true
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: "./app"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use nodejs
        uses: actions/setup-node@v4

      - name: Install deps
        run: npm ci
        
      - name: Run build
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-dist
          path: app/dist/

  deploy:
    needs: ["lint", "test", "build"]
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./terraform/prod"
    env:
      TF_VAR_github_org: ${{ secrets.ORGANIZATION_NAME }}
      TF_VAR_github_repository: ${{ secrets.REPOSITORY_NAME }}
      TF_VAR_s3_bucket_name: ${{ secrets.S3_BUCKET_NAME  }}
      TF_VAR_website_domain: ${{ secrets.WEBSITE_DOMAIN  }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: app-dist
          path: app/dist

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "^1.3.7"
            # terraform_wrapper: false

      - name: Terraform format
        id: fmt
        run: terraform fmt -recursive -check -diff
        continue-on-error: true

      - name: Terraform init
        id: init
        run: |
          terraform init \
            -backend-config="bucket=${{ env.TFSTATE_BUCKET }}" \
            -backend-config="key=state/terraform.tfstate" \
            -backend-config="region=${{ env.AWS_REGION  }}" \
            -backend-config="encrypt=true"

      - name: Terraform validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve

      - name: Deploy build files to S3
        id: upload
        run: |
          aws s3 sync app/dist s3:${{ secrets.S3_BUCKET_NAME }} --delete
