name: "Destroy AWS"

on:
  workflow_dispatch:

env:
  AWS_REGION : "ap-northeast-1"
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
  TFSTATE_BUCKET: ${{ secrets.TFSTATE_BUCKET }}

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    name: Destroy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: "./terraform/prod"
    env:
      TF_VAR_github_org: ${{ secrets.ORGANIZATION_NAME }}
      TF_VAR_github_repository: ${{ secrets.REPOSITORY_NAME }}
      TF_VAR_s3_bucket_name: ${{ secrets.S3_BUCKET_NAME  }}
      TF_VAR_website_domain: ${{ secrets.WEBSITE_DOMAIN  }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "^1.3.7"
            # terraform_wrapper: false

      - name: Terraform format
        id: fmt
        run: terraform fmt -recursive -check -diff
        continue-on-error: true

      - name: Terraform init
        id: init
        run: |
          terraform init \
            -backend-config="bucket=${{ env.TFSTATE_BUCKET }}" \
            -backend-config="key=state/terraform.tfstate" \
            -backend-config="region=${{ env.AWS_REGION  }}" \
            -backend-config="encrypt=true"

      - name: Terraform destroy
        id: destroy
        run: terraform destroy -auto-approve

